### ISSUE TITLE
Excessive Backspace on Physical Keyboard Disables Input

### ISSUE THREAD

**Issue by MichaelDRichards** [utkarsh1311/wordle-clone#1]
When using a physical keyboard, if a user presses the Backspace key more times than there are letters on the board, the game will stop accepting input either with the physical keyboard or the on screen keyboard.

Win 10
Firefox 96.0.2
Chrome 97.0.4692.99

**Comment by utkarsh1311** [comment]
Hey @MichaelDRichards. Thank you for finding this bug. Would you like to work on it?

**Comment by MichaelDRichards** [comment]
> Hey @MichaelDRichards. Thank you for finding this bug. Would you like to work on it?

I would but I don't know anything about FE stuff 😃

**Comment by pankaj2961** [comment]
Hi @utkarsh1311   I can fix this. can i take this bug

**Comment by utkarsh1311** [comment]
@pankaj2961 Ya sure. Go ahead.

**Comment by utkarsh1311** [comment]
fixed with PR #2
