### ISSUE TITLE
Update the `README.md`

### ISSUE THREAD

**Issue by utkarsh1311** [utkarsh1311/wordle-clone#3]
Update the README so that users can understand the project in a better way.

**Comment by Khusyasy** [comment]
Hi @utkarsh1311 

I'm interested to help, can you give more info about this?

**Comment by utkarsh1311** [comment]
Hey @Khusyasy. You can add some screenshots of the game to the README. 
Also add a discription about the game and instructions on how to play it.

**Comment by Khusyasy** [comment]
Sure, I'll start working on it
